### ISSUE TITLE
Same txs is accepted by endorsement, orderers, but rejected by validator with TxValidationCode_DUPLICATE_TXID

### ISSUE THREAD

**Issue by fubss** [scientificideas/fabric#15]
Detected the situation when two the same transactions with the same tx-id were endorsed and accepted by ordering services, then first tx was accepted successfully by validation peers, but the second was rejected because of TxValidationCode_DUPLICATE_TXID . 
Is it normal behaviour or not? Looks like not 
I can share blocks with this case privately.

**Comment by pfi79** [comment]
It's normal behaviour.

The cause is most likely in your client and the sdk you are using.

But most importantly, a transaction with one txid will be applied to a state only once.
